<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit69f78bc9fe54b761b6a3eb904fe8fe01
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WoofSchemaBuilder\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WoofSchemaBuilder\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit69f78bc9fe54b761b6a3eb904fe8fe01::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit69f78bc9fe54b761b6a3eb904fe8fe01::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit69f78bc9fe54b761b6a3eb904fe8fe01::$classMap;

        }, null, ClassLoader::class);
    }
}
